// Bird life list — dynamic count, Pokémon-style stats per bird
window.BIRD_DATA = [
  { num: 1, name: "Red-billed Blue-Magpie", sci: "Urocissa erythroryncha", date: "06 Nov 2025", loc: "On the way to Kanatal, Uttarakhand", habitat: "Forest", behavior: "Forager", region: "Himalayan", rarity: "Rare", hp: 75, title: "The Sapphire Trickster", stats: { speed: 70, stamina: 60, stealth: 35, intelligence: 95, charm: 45, vocal: 80 }, move: { name: "Sapphire Trail", desc: "Whips its 60cm tail through the canopy in a blue blur that dazzles onlookers and warns intruders." }, facts: ["Long blue tail can be 2x its body length", "Highly intelligent corvid", "Known for raucous, varied calls"] },
  { num: 2, name: "Greater Coucal", sci: "Centropus sinensis", date: "06 Nov 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 85, title: "The Hidden Hunter", stats: { speed: 50, stamina: 65, stealth: 75, intelligence: 70, charm: 50, vocal: 75 }, move: { name: "Sonic Boom", desc: "Releases a deep booming call that carries over a kilometre, asserting territory." }, facts: ["Member of the cuckoo family but not a brood parasite", "Eats snakes, lizards, and insects", "Deep booming call"] },
  { num: 3, name: "White-cheeked Barbet", sci: "Psilopogon viridis", date: "06 Nov 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Climber", region: "South Indian", rarity: "Uncommon", hp: 55, title: "The Hollow Carver", stats: { speed: 55, stamina: 55, stealth: 65, intelligence: 60, charm: 55, vocal: 80 }, move: { name: "Kotur Drill", desc: "Excavates a perfect nest cavity while broadcasting a hypnotic 'kotur-kotur' loop." }, facts: ["Endemic to peninsular India", "Loud monotonous 'kotur-kotur' call", "Excavates nest holes in trees"] },
  { num: 4, name: "Ashy Drongo", sci: "Dicrurus leucophaeus", date: "06 Nov 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 60, title: "The Mimic Ninja", stats: { speed: 88, stamina: 70, stealth: 50, intelligence: 85, charm: 45, vocal: 85 }, move: { name: "Ghost Call", desc: "Mimics another species' alarm call to scare it off a meal, then steals the spoils." }, facts: ["Catches insects mid-air", "Excellent mimic of other birds", "Forked tail for agile flight"] },
  { num: 5, name: "Asian Tit", sci: "Parus cinereus", date: "06 Nov 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Songbird", region: "Pan-Indian", rarity: "Common", hp: 35, title: "The Cheerful Scout", stats: { speed: 75, stamina: 50, stealth: 55, intelligence: 75, charm: 70, vocal: 75 }, move: { name: "Flock Chorus", desc: "Leads mixed-species foraging parties with a relentless cheerful song." }, facts: ["Cousin of the European Great Tit", "Black-and-white head pattern", "Cheerful 'chichipee' song"] },
  { num: 6, name: "Red-wattled Lapwing", sci: "Vanellus indicus", date: "27 Nov 2025", loc: "Nirvana River Resort, Uttarakhand", habitat: "Wetland", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 70, title: "The Sleepless Sentinel", stats: { speed: 75, stamina: 75, stealth: 50, intelligence: 65, charm: 40, vocal: 80 }, move: { name: "Did-He-Do-It!", desc: "Shrieks its iconic alarm and mobs any intruder that wanders near the nest." }, facts: ["Famous 'did-he-do-it' call", "Fiercely defends nest from intruders", "Lays eggs on bare ground"] },
  { num: 7, name: "Brown Dipper", sci: "Cinclus pallasii", date: "27 Nov 2025", loc: "Nirvana River Resort, Uttarakhand", habitat: "Wetland", behavior: "Forager", region: "Himalayan", rarity: "Epic", hp: 55, title: "The Underwater Walker", stats: { speed: 70, stamina: 75, stealth: 60, intelligence: 60, charm: 40, vocal: 50 }, move: { name: "Hydro Walk", desc: "Strolls along the stream bed underwater, defying current and gravity." }, facts: ["Walks underwater along stream beds", "Has a transparent third eyelid", "Found only along fast mountain streams"] },
  { num: 8, name: "Plumbeous Redstart", sci: "Phoenicurus fuliginosus", date: "27 Nov 2025", loc: "Nirvana River Resort, Uttarakhand", habitat: "Wetland", behavior: "Songbird", region: "Himalayan", rarity: "Rare", hp: 40, title: "The Stream Spinner", stats: { speed: 80, stamina: 65, stealth: 45, intelligence: 55, charm: 50, vocal: 75 }, move: { name: "Tail Flare", desc: "Constantly fans its rusty-red tail in a hypnotic flicker that mesmerises insects." }, facts: ["Constantly fans its rusty-red tail", "Lives along Himalayan streams", "Males slate-blue, females gray"] },
  { num: 9, name: "White-capped Redstart", sci: "Phoenicoprocne leucocephala", date: "27 Nov 2025", loc: "Nirvana River Resort, Uttarakhand", habitat: "Wetland", behavior: "Songbird", region: "Himalayan", rarity: "Rare", hp: 45, title: "The Crowned Pebble-Dancer", stats: { speed: 78, stamina: 70, stealth: 40, intelligence: 55, charm: 50, vocal: 75 }, move: { name: "Royal Bow", desc: "Bobs its white-crowned head against river rocks in a ritualised territorial dance." }, facts: ["Striking white crown on black head", "Bobs body up and down on rocks", "Migrates to lower altitudes in winter"] },
  { num: 10, name: "Brown-fronted Woodpecker", sci: "Dendrocoptes auriceps", date: "27 Nov 2025", loc: "Near Oakwood Forest Retreat, Uttarakhand", habitat: "Forest", behavior: "Climber", region: "Himalayan", rarity: "Rare", hp: 55, title: "The Oak Drummer", stats: { speed: 60, stamina: 70, stealth: 60, intelligence: 70, charm: 40, vocal: 70 }, move: { name: "Thunder Drum", desc: "Beats a tree trunk 20 times per second; the percussion echoes through Himalayan oak forests." }, facts: ["Drums on tree trunks for territory", "Specialized tongue 3x its bill length", "Endemic to Himalayan oak forests"] },
  { num: 11, name: "Eurasian Jay", sci: "Garrulus glandarius", date: "27 Nov 2025", loc: "Near Oakwood Forest Retreat, Uttarakhand", habitat: "Forest", behavior: "Forager", region: "Himalayan", rarity: "Rare", hp: 65, title: "The Acorn Hoarder", stats: { speed: 70, stamina: 75, stealth: 60, intelligence: 95, charm: 45, vocal: 80 }, move: { name: "Memory Vault", desc: "Caches thousands of acorns each autumn and remembers most of them by spring." }, facts: ["Caches thousands of acorns each autumn", "Can mimic hawks and other birds", "Brilliant blue wing patch"] },
  { num: 12, name: "Streaked Laughingthrush", sci: "Trochalopteron lineatum", date: "27 Nov 2025", loc: "Near Oakwood Forest Retreat, Uttarakhand", habitat: "Forest", behavior: "Songbird", region: "Himalayan", rarity: "Rare", hp: 55, title: "The Hilarious Heckler", stats: { speed: 65, stamina: 70, stealth: 55, intelligence: 70, charm: 55, vocal: 90 }, move: { name: "Forest Laughter", desc: "The whole flock erupts in manic cackling, drowning out every predator's call." }, facts: ["Travels in noisy social flocks", "Named for laughter-like calls", "Forages on forest floor"] },
  { num: 13, name: "Rufous Sibia", sci: "Heterophasia capistrata", date: "27 Nov 2025", loc: "Near Oakwood Forest Retreat, Uttarakhand", habitat: "Forest", behavior: "Songbird", region: "Himalayan", rarity: "Rare", hp: 55, title: "The Oak Singer", stats: { speed: 70, stamina: 65, stealth: 50, intelligence: 65, charm: 50, vocal: 90 }, move: { name: "Whistle of the Pines", desc: "A piercing, sweet whistle that defines Himalayan oak forests at dawn." }, facts: ["Melodious whistling song", "Striking black-headed, rufous body", "Common in Himalayan oak forests"] },
  { num: 14, name: "Chestnut-bellied Rock-Thrush", sci: "Monticola rufiventris", date: "27 Nov 2025", loc: "Near Oakwood Forest Retreat, Uttarakhand", habitat: "Mountain", behavior: "Songbird", region: "Himalayan", rarity: "Epic", hp: 50, title: "The Cliffside Bard", stats: { speed: 70, stamina: 75, stealth: 55, intelligence: 60, charm: 40, vocal: 85 }, move: { name: "Mountain Anthem", desc: "Sings from a high rocky perch; the song carries across entire valleys." }, facts: ["Males flash brilliant blue and chestnut", "Sings from prominent rocky perches", "Migrates altitudinally with seasons"] },
  { num: 15, name: "Blue Whistling-Thrush", sci: "Myophonus caeruleus", date: "27 Nov 2025", loc: "Near Landour Bakehouse, Uttarakhand", habitat: "Mountain", behavior: "Songbird", region: "Himalayan", rarity: "Rare", hp: 65, title: "The Whistling Ghost", stats: { speed: 65, stamina: 70, stealth: 60, intelligence: 70, charm: 45, vocal: 95 }, move: { name: "Ghost Whistle", desc: "Looses an eerie, human-like whistle that drifts through mountain mist." }, facts: ["Eerie human-like whistling song", "Deep blue plumage with sparkles", "Often seen near mountain streams"] },
  { num: 16, name: "Asian Green Bee-eater", sci: "Merops orientalis", date: "27 Nov 2025", loc: "Godrej Ecity, Karnataka", habitat: "Grassland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 50, title: "The Emerald Aerialist", stats: { speed: 92, stamina: 80, stealth: 30, intelligence: 70, charm: 55, vocal: 70 }, move: { name: "Sting Strip", desc: "Snatches a wasp mid-flight, then de-stings it with a sharp rub of the perch." }, facts: ["Catches bees and wasps mid-flight", "Removes stingers by rubbing on perch", "Brilliant emerald-green plumage"] },
  { num: 17, name: "Small Minivet", sci: "Pericrocotus cinnamomeus", date: "27 Nov 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 35, title: "The Flame Mote", stats: { speed: 80, stamina: 55, stealth: 35, intelligence: 55, charm: 45, vocal: 70 }, move: { name: "Ember Flit", desc: "Darts through the canopy as a tiny living spark of orange and black." }, facts: ["Males are flame-orange and black", "Travels in mixed-species flocks", "Tiny — barely 16cm long"] },
  { num: 18, name: "Himalayan Woodpecker", sci: "Dendrocopos himalayensis", date: "03 Dec 2025", loc: "Surkanda Devi Temple, Uttarakhand", habitat: "Mountain", behavior: "Climber", region: "Himalayan", rarity: "Epic", hp: 70, title: "The Mountain Drummer", stats: { speed: 60, stamina: 75, stealth: 60, intelligence: 75, charm: 35, vocal: 70 }, move: { name: "Avalanche Beat", desc: "Hammers conifer bark hard enough to shake snow off the branches." }, facts: ["Endemic to the western Himalayas", "Drums up to 20 times per second", "Striking red crown on males"] },
  { num: 19, name: "Gray Treepie", sci: "Dendrocitta formosae", date: "03 Dec 2025", loc: "Near Oakwood Forest Retreat, Uttarakhand", habitat: "Forest", behavior: "Forager", region: "Himalayan", rarity: "Uncommon", hp: 60, title: "The Long-Tailed Rogue", stats: { speed: 65, stamina: 65, stealth: 50, intelligence: 90, charm: 55, vocal: 80 }, move: { name: "Tail Rudder", desc: "Uses its long graduated tail as a rudder through dense forest, escaping any pursuer." }, facts: ["Long graduated tail", "Highly social and noisy", "Member of the crow family"] },
  { num: 20, name: "Himalayan Bulbul", sci: "Pycnonotus leucogenys", date: "03 Dec 2025", loc: "Kanatal, Uttarakhand", habitat: "Mountain", behavior: "Songbird", region: "Himalayan", rarity: "Uncommon", hp: 45, title: "The Crested Carol", stats: { speed: 65, stamina: 60, stealth: 50, intelligence: 60, charm: 70, vocal: 85 }, move: { name: "Four-Note Cheer", desc: "A bright four-note song that announces sunrise in every Himalayan hill station." }, facts: ["Distinctive pointed black crest", "Cheerful four-note song", "Common around hill stations"] },
  { num: 21, name: "Black-headed Jay", sci: "Garrulus lanceolatus", date: "04 Dec 2025", loc: "Kanatal, Uttarakhand", habitat: "Forest", behavior: "Forager", region: "Himalayan", rarity: "Epic", hp: 65, title: "The Cobalt Conspirator", stats: { speed: 70, stamina: 70, stealth: 55, intelligence: 92, charm: 50, vocal: 80 }, move: { name: "Mimic Mayhem", desc: "Imitates raptor calls to clear other birds off a food source it wants." }, facts: ["Distinctive crested black head", "Endemic to western Himalayas", "Mimics calls of other forest birds"] },
  { num: 22, name: "White-tailed Nuthatch", sci: "Sitta himalayensis", date: "04 Dec 2025", loc: "Kanatal, Uttarakhand", habitat: "Forest", behavior: "Climber", region: "Himalayan", rarity: "Rare", hp: 40, title: "The Upside-Down Climber", stats: { speed: 65, stamina: 60, stealth: 55, intelligence: 75, charm: 50, vocal: 65 }, move: { name: "Gravity Flip", desc: "Walks headfirst DOWN tree trunks to find insects no other bird can reach." }, facts: ["Walks down tree trunks headfirst", "White flash on tail in flight", "Wedges nuts to crack them open"] },
  { num: 23, name: "Jungle Owlet", sci: "Glaucidium radiatum", date: "13 Dec 2025", loc: "Near a homestay, Kerala", habitat: "Forest", behavior: "Hunter", region: "Western Ghats", rarity: "Epic", hp: 70, title: "The Daylight Owl", stats: { speed: 75, stamina: 70, stealth: 90, intelligence: 80, charm: 30, vocal: 65 }, move: { name: "Noon Ambush", desc: "Hunts in broad daylight when no one expects an owl; near-perfect surprise attacks." }, facts: ["Active by day unlike most owls", "Tiny — only 20cm tall", "Distinctive barred plumage"] },
  { num: 24, name: "Greater Racket-tailed Drongo", sci: "Dicrurus paradiseus", date: "13 Dec 2025", loc: "Near a homestay, Kerala", habitat: "Forest", behavior: "Hunter", region: "Western Ghats", rarity: "Legendary", hp: 80, title: "The Master Mimic", stats: { speed: 88, stamina: 75, stealth: 50, intelligence: 95, charm: 40, vocal: 100 }, move: { name: "Symphony of Lies", desc: "Mimics 35+ species in a single performance; leads or deceives entire forest flocks." }, facts: ["Two long tail wires with paddle tips", "Master mimic of 35+ bird species", "Leads mixed-species foraging flocks"] },
  { num: 25, name: "Rufous Treepie", sci: "Dendrocitta vagabunda", date: "13 Dec 2025", loc: "Near a homestay, Kerala", habitat: "Forest", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 65, title: "The Bold Vagabond", stats: { speed: 70, stamina: 70, stealth: 45, intelligence: 90, charm: 65, vocal: 80 }, move: { name: "Metallic Cry", desc: "A piercing 'KO-TREE!' that announces the rogue's arrival from a kilometre away." }, facts: ["Bold and curious — often near humans", "Striking rufous and black plumage", "Loud metallic 'ko-tree' call"] },
  { num: 26, name: "Southern Hill Myna", sci: "Gracula indica", date: "13 Dec 2025", loc: "Near a homestay, Kerala", habitat: "Forest", behavior: "Songbird", region: "Western Ghats", rarity: "Legendary", hp: 70, title: "The Voice Thief", stats: { speed: 70, stamina: 70, stealth: 40, intelligence: 95, charm: 55, vocal: 100 }, move: { name: "Mirror Tongue", desc: "Perfectly mimics any sound it hears, including human speech, with eerie clarity." }, facts: ["One of the world's best mimics", "Bright orange wattles on head", "Can imitate human speech with clarity"] },
  { num: 27, name: "Indian White-eye", sci: "Zosterops palpebrosus", date: "13 Dec 2025", loc: "Near an Airbnb, Tamil Nadu", habitat: "Forest", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 30, title: "The Bespectacled Sprite", stats: { speed: 80, stamina: 50, stealth: 50, intelligence: 60, charm: 65, vocal: 65 }, move: { name: "Nectar Rush", desc: "Buzzes through blooms in a chattering swarm, draining every flower in seconds." }, facts: ["Tiny olive-green bird with white eye-ring", "Sips nectar from flowers", "Travels in chattering flocks"] },
  { num: 28, name: "Tickell's Blue Flycatcher", sci: "Cyornis tickelliae", date: "13 Dec 2025", loc: "Near an Airbnb, Tamil Nadu", habitat: "Forest", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 40, title: "The Azure Sniper", stats: { speed: 85, stamina: 60, stealth: 50, intelligence: 65, charm: 50, vocal: 80 }, move: { name: "Aerial Snatch", desc: "Sallies from a low perch and snatches an insect mid-flight with surgical precision." }, facts: ["Brilliant blue with orange throat", "Sallies out to catch insects mid-air", "Sweet musical song"] },
  { num: 29, name: "Purple-rumped Sunbird", sci: "Leptocoma zeylonica", date: "13 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "South Indian", rarity: "Common", hp: 30, title: "The Iridescent Sip", stats: { speed: 88, stamina: 55, stealth: 35, intelligence: 55, charm: 70, vocal: 60 }, move: { name: "Hover Sip", desc: "Hovers like a hummingbird, drains a flower, and flickers away in a glint of purple." }, facts: ["Iridescent purple rump glints in sun", "Hovers like a hummingbird at flowers", "Tiny — only 10cm long"] },
  { num: 30, name: "Blue-tailed Bee-eater", sci: "Merops philippinus", date: "13 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Grassland", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 55, title: "The Sky Streamer", stats: { speed: 92, stamina: 85, stealth: 30, intelligence: 70, charm: 50, vocal: 70 }, move: { name: "Dragonfly Snap", desc: "Plucks a dragonfly out of the air at full speed, never breaking its glide." }, facts: ["Long streaming central tail feathers", "Catches dragonflies and bees mid-air", "Migratory across South Asia"] },
  { num: 31, name: "White-throated Kingfisher", sci: "Halcyon smyrnensis", date: "13 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 65, title: "The Turquoise Diver", stats: { speed: 85, stamina: 70, stealth: 50, intelligence: 70, charm: 55, vocal: 80 }, move: { name: "Plunge Strike", desc: "Dives from a fixed perch and impales prey on a brilliant red dagger of a bill." }, facts: ["Eats more insects than fish", "Brilliant turquoise back, red bill", "Loud cackling laugh-like call"] },
  { num: 32, name: "Indian Golden Oriole", sci: "Oriolus kundoo", date: "13 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Songbird", region: "Pan-Indian", rarity: "Uncommon", hp: 55, title: "The Golden Whistler", stats: { speed: 75, stamina: 70, stealth: 50, intelligence: 65, charm: 50, vocal: 90 }, move: { name: "Pee-Loo-Loo", desc: "A fluty, golden whistle that turns the entire canopy into a concert hall." }, facts: ["Brilliant golden-yellow with black wings", "Fluty 'pee-loo-loo' whistle", "Builds hammock-like nests"] },
  { num: 33, name: "Black Drongo", sci: "Dicrurus macrocercus", date: "13 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Grassland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 60, title: "The Fearless Fork", stats: { speed: 88, stamina: 70, stealth: 40, intelligence: 80, charm: 55, vocal: 80 }, move: { name: "Sky Strike", desc: "Dive-bombs hawks and crows three times its size; absolutely fears nothing." }, facts: ["Fearlessly attacks crows and hawks", "Often rides on cattle to catch insects", "Deep forked 'fish-tail' shape"] },
  { num: 34, name: "Red-vented Bulbul", sci: "Pycnonotus cafer", date: "13 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Songbird", region: "Pan-Indian", rarity: "Common", hp: 45, title: "The Garden Minstrel", stats: { speed: 70, stamina: 55, stealth: 40, intelligence: 65, charm: 80, vocal: 85 }, move: { name: "Ginger-Beer Song", desc: "A cheerful repeating phrase that becomes the soundtrack of every Indian garden." }, facts: ["India's most common garden bird", "Bright red patch under tail", "Cheerful 'ginger-beer' song"] },
  { num: 35, name: "Rose-ringed Parakeet", sci: "Psittacula krameri", date: "16 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 70, title: "The Emerald Mimic", stats: { speed: 80, stamina: 75, stealth: 30, intelligence: 90, charm: 75, vocal: 95 }, move: { name: "Voice Steal", desc: "Repeats human speech with uncanny clarity; greets you back when you say hello." }, facts: ["Can live 30+ years in the wild", "Males have a pink-and-black neck ring", "Excellent mimic of human speech"] },
  { num: 36, name: "Ashy Woodswallow", sci: "Artamus fuscus", date: "16 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Sky", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 50, title: "The Cloud Glider", stats: { speed: 80, stamina: 90, stealth: 30, intelligence: 65, charm: 55, vocal: 70 }, move: { name: "Endless Glide", desc: "One of the only perching birds that soars; can stay aloft for hours catching insects." }, facts: ["Cluster together on bare branches", "Glides in circles catching flying insects", "One of few perching birds that soar"] },
  { num: 37, name: "Indian Paradise-Flycatcher", sci: "Terpsiphone paradisi", date: "16 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Hunter", region: "Pan-Indian", rarity: "Epic", hp: 55, title: "The Ribbon-Tailed King", stats: { speed: 80, stamina: 70, stealth: 35, intelligence: 70, charm: 40, vocal: 75 }, move: { name: "Streamer Strike", desc: "Trails 30cm tail ribbons that flutter like a banner during every hunting dive." }, facts: ["Males grow tail streamers up to 30cm", "Plumage shifts from rufous to white with age", "Often called 'Doodhraj' (king of milk)"] },
  { num: 38, name: "Red-whiskered Bulbul", sci: "Pycnonotus jocosus", date: "16 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Songbird", region: "Pan-Indian", rarity: "Common", hp: 45, title: "The Punk Bulbul", stats: { speed: 70, stamina: 55, stealth: 40, intelligence: 65, charm: 80, vocal: 90 }, move: { name: "Crested Serenade", desc: "Lifts its punk-rock crest and breaks into a melody for its lifelong mate." }, facts: ["Distinctive black crest and red 'whiskers'", "Cheerful melodious song", "Pairs mate for life"] },
  { num: 39, name: "Chestnut-tailed Starling", sci: "Sturnia malabarica", date: "16 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 55, title: "The Chattering Silver", stats: { speed: 75, stamina: 70, stealth: 50, intelligence: 75, charm: 60, vocal: 80 }, move: { name: "Flock Frenzy", desc: "Strips a flowering tree in minutes with a chattering, organised squadron." }, facts: ["Travels in noisy chattering flocks", "Pale silver head with dark eyes", "Eats fruit and nectar from flowering trees"] },
  { num: 40, name: "Common Myna", sci: "Acridotheres tristis", date: "16 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 55, title: "The Streetwise Trickster", stats: { speed: 70, stamina: 65, stealth: 45, intelligence: 90, charm: 80, vocal: 80 }, move: { name: "Tool Trick", desc: "Uses any nearby object to pry food loose; one of the world's most adaptable birds." }, facts: ["Among the world's top 100 invasive species", "Highly intelligent — can use tools", "Bright yellow eye-patch and legs"] },
  { num: 41, name: "Spotted Dove", sci: "Spilopelia chinensis", date: "17 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 50, title: "The Polka-Dot Cooer", stats: { speed: 65, stamina: 60, stealth: 50, intelligence: 50, charm: 80, vocal: 65 }, move: { name: "Soft Coo", desc: "A soothing 'krookru-krookroo' that lulls predators into looking elsewhere." }, facts: ["Distinctive black-and-white spotted neck patch", "Soft cooing 'krookru-krookroo' call", "Builds flimsy stick nests"] },
  { num: 42, name: "Asian Koel", sci: "Eudynamys scolopaceus", date: "17 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 65, title: "The Cuckoo Imposter", stats: { speed: 75, stamina: 70, stealth: 70, intelligence: 85, charm: 45, vocal: 95 }, move: { name: "Foster Plot", desc: "Sneaks eggs into a crow's nest; the koel chick is raised by unwitting parents." }, facts: ["Brood parasite — lays eggs in crow nests", "Loud 'koo-Ooo' call heralds summer", "Males glossy black, females spotted brown"] },
  { num: 43, name: "Pied Bushchat", sci: "Saxicola caprata", date: "17 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Grassland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 40, title: "The Tuxedo Sentinel", stats: { speed: 75, stamina: 60, stealth: 45, intelligence: 60, charm: 65, vocal: 75 }, move: { name: "Perch Pounce", desc: "Snaps insects off grass blades from a roadside fence with perfect timing." }, facts: ["Males boldly black-and-white", "Perches on grass stems and fence posts", "Sweet whistling song"] },
  { num: 44, name: "Spot-breasted Fantail", sci: "Rhipidura albogularis", date: "19 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Hunter", region: "South Indian", rarity: "Rare", hp: 35, title: "The Fan Dancer", stats: { speed: 85, stamina: 60, stealth: 30, intelligence: 60, charm: 60, vocal: 75 }, move: { name: "Pirouette Flush", desc: "Spins with tail fanned wide to scare insects out of hiding, then snatches them." }, facts: ["Constantly fans tail like a peacock", "Pirouettes to flush insects", "Endemic to peninsular India"] },
  { num: 45, name: "Purple Sunbird", sci: "Cinnyris asiaticus", date: "19 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 30, title: "The Iridescent Hum", stats: { speed: 88, stamina: 55, stealth: 35, intelligence: 55, charm: 70, vocal: 60 }, move: { name: "Nectar Hover", desc: "Briefly hovers like a hummingbird to drain a flower nobody else can reach." }, facts: ["Males iridescent purple-black in breeding plumage", "Can hover briefly like a hummingbird", "Curved bill perfect for nectar"] },
  { num: 46, name: "Black Kite", sci: "Milvus migrans", date: "19 Dec 2025", loc: "Bengaluru, Karnataka", habitat: "Sky", behavior: "Raptor", region: "Pan-Indian", rarity: "Common", hp: 100, title: "The Urban Sky-Lord", stats: { speed: 80, stamina: 90, stealth: 50, intelligence: 85, charm: 40, vocal: 70 }, move: { name: "Mid-Air Snatch", desc: "Plucks food right out of a human's hand in busy city skies." }, facts: ["Among the most abundant raptors on Earth", "Distinctive forked tail", "Famous for snatching food mid-air in cities"] },
  { num: 47, name: "Brahminy Kite", sci: "Haliastur indus", date: "24 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Sky", behavior: "Raptor", region: "Pan-Indian", rarity: "Uncommon", hp: 100, title: "Garuda's Echo", stats: { speed: 80, stamina: 85, stealth: 55, intelligence: 80, charm: 35, vocal: 65 }, move: { name: "Sacred Dive", desc: "Plummets to the water to snatch a fish; the form sacred to Hindu mythology." }, facts: ["Striking white head and chestnut body", "Often seen near water hunting fish", "Sacred to Hindu mythology — Garuda's form"] },
  { num: 48, name: "Shikra", sci: "Accipiter badius", date: "26 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Raptor", region: "Pan-Indian", rarity: "Uncommon", hp: 85, title: "The Silent Strike", stats: { speed: 92, stamina: 75, stealth: 85, intelligence: 85, charm: 25, vocal: 60 }, move: { name: "Surprise Strike", desc: "Ambushes prey with a sudden low burst out of cover; over before it began." }, facts: ["Small but fierce hawk", "Ambushes prey with surprise attacks", "Used in falconry for centuries"] },
  { num: 49, name: "Large-billed Crow", sci: "Corvus macrorhynchos", date: "26 Dec 2025", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 90, title: "The Face Reader", stats: { speed: 70, stamina: 80, stealth: 50, intelligence: 100, charm: 70, vocal: 80 }, move: { name: "Memory of Faces", desc: "Remembers individual human faces for years; holds grudges and returns favours." }, facts: ["Among the most intelligent birds", "Can recognize individual human faces", "Massive bill for varied diet"] },
  { num: 50, name: "Black-winged Kite", sci: "Elanus caeruleus", date: "16 Jan 2026", loc: "Godrej Ecity, Karnataka", habitat: "Grassland", behavior: "Raptor", region: "Pan-Indian", rarity: "Uncommon", hp: 85, title: "The Red-Eyed Hoverer", stats: { speed: 80, stamina: 85, stealth: 50, intelligence: 80, charm: 35, vocal: 60 }, move: { name: "Hover Drop", desc: "Hovers like a helicopter over open fields, then drops straight onto a rodent." }, facts: ["Striking red eyes", "Hovers like a kestrel before diving", "Hunts small rodents in open fields"] },
  { num: 51, name: "Rosy Starling", sci: "Pastor roseus", date: "25 Jan 2026", loc: "Godrej Ecity, Karnataka", habitat: "Grassland", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 55, title: "The Pink Tide", stats: { speed: 80, stamina: 95, stealth: 40, intelligence: 75, charm: 55, vocal: 75 }, move: { name: "Million Flock", desc: "Arrives in flocks of millions that darken the sky and strip fields bare." }, facts: ["Migrates from Central Asia each winter", "Flocks can number in millions", "Pink-and-black breeding plumage"] },
  { num: 52, name: "Alexandrine Parakeet", sci: "Psittacula eupatria", date: "25 Jan 2026", loc: "Bengaluru, Karnataka", habitat: "Forest", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 85, title: "The Conqueror's Parrot", stats: { speed: 75, stamina: 80, stealth: 30, intelligence: 92, charm: 70, vocal: 95 }, move: { name: "Royal Speech", desc: "Mimics human voices for decades; named after Alexander the Great himself." }, facts: ["Named after Alexander the Great", "Largest parakeet in India", "Can live up to 40 years"] },
  { num: 53, name: "Pale-billed Flowerpecker", sci: "Dicaeum erythrorhynchos", date: "26 Jan 2026", loc: "Godrej Ecity, Karnataka", habitat: "Urban", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 25, title: "The Tiny Tick", stats: { speed: 85, stamina: 45, stealth: 55, intelligence: 55, charm: 60, vocal: 55 }, move: { name: "Mistletoe Drop", desc: "Eats mistletoe berries and disperses seeds; tiny gardener of the canopy." }, facts: ["One of the smallest birds in India — 8cm", "Disperses mistletoe seeds", "Constant high-pitched 'chik-chik' calls"] },
  { num: 54, name: "Indian Pond-Heron", sci: "Ardeola grayii", date: "06 Feb 2026", loc: "Godrej Ecity, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 70, title: "The Reedside Phantom", stats: { speed: 50, stamina: 70, stealth: 95, intelligence: 75, charm: 40, vocal: 40 }, move: { name: "Phantom Reveal", desc: "Stands invisible against reeds, then erupts into flight as a sudden white blur." }, facts: ["Drab brown standing, flashes white in flight", "Stalks fish with extreme patience", "Master of disguise at water's edge"] },
  { num: 55, name: "Eurasian Coot", sci: "Fulica atra", date: "15 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Waterfowl", region: "Pan-Indian", rarity: "Common", hp: 70, title: "The Lobed-Foot Brawler", stats: { speed: 55, stamina: 75, stealth: 40, intelligence: 65, charm: 45, vocal: 60 }, move: { name: "Water Slap", desc: "Charges across the lake surface in a thrashing aggressive display; nobody messes with a coot." }, facts: ["White bill and forehead shield", "Lobed toes instead of webbed feet", "Aggressive territorial fights on water"] },
  { num: 56, name: "Gray-headed Swamphen", sci: "Porphyrio poliocephalus", date: "15 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Forager", region: "Pan-Indian", rarity: "Common", hp: 80, title: "The Marsh Royal", stats: { speed: 55, stamina: 70, stealth: 45, intelligence: 75, charm: 50, vocal: 65 }, move: { name: "Foot Grip", desc: "Holds food in one foot like a human hand while balancing on floating reeds." }, facts: ["Large purple-blue waterbird with red bill", "Holds food in foot like a hand", "Walks on floating vegetation"] },
  { num: 57, name: "Wood Sandpiper", sci: "Tringa glareola", date: "15 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 45, title: "The Arctic Wanderer", stats: { speed: 75, stamina: 95, stealth: 65, intelligence: 60, charm: 45, vocal: 60 }, move: { name: "Bobbing Probe", desc: "Wades and bobs constantly; flies thousands of kilometres from the Arctic each year." }, facts: ["Long-distance migrant from Arctic", "Bobs body while wading", "Speckled brown plumage"] },
  { num: 58, name: "Indian Cormorant", sci: "Phalacrocorax fuscicollis", date: "15 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 80, title: "The Black Diver", stats: { speed: 65, stamina: 80, stealth: 55, intelligence: 75, charm: 45, vocal: 40 }, move: { name: "Underwater Pursuit", desc: "Chases fish underwater; surfaces with breakfast almost every time." }, facts: ["Dives underwater to chase fish", "Wings spread to dry after fishing", "Slim profile distinguishes from other cormorants"] },
  { num: 59, name: "Little Egret", sci: "Egretta garzetta", date: "15 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 70, title: "The Yellow-Footed Ghost", stats: { speed: 65, stamina: 70, stealth: 75, intelligence: 75, charm: 40, vocal: 45 }, move: { name: "Foot Stir", desc: "Shuffles bright yellow feet underwater to spook fish into the open." }, facts: ["Bright yellow feet contrast black legs", "Stirs water with feet to flush fish", "Pure white plumage with delicate plumes"] },
  { num: 60, name: "Spotted Owlet", sci: "Athene brama", date: "17 Mar 2026", loc: "Bengaluru, Karnataka", habitat: "Urban", behavior: "Raptor", region: "Pan-Indian", rarity: "Uncommon", hp: 65, title: "The Bobbing Watcher", stats: { speed: 70, stamina: 65, stealth: 85, intelligence: 85, charm: 45, vocal: 80 }, move: { name: "Head Bob", desc: "Bobs its head in eerie patterns to triangulate distance before striking." }, facts: ["Active at dusk and dawn", "Famous for bobbing head movements", "Often roosts in old buildings and trees"] },
  { num: 61, name: "Indian Spot-billed Duck", sci: "Anas poecilorhyncha", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Waterfowl", region: "Pan-Indian", rarity: "Common", hp: 90, title: "The Red-Spotted Dabbler", stats: { speed: 70, stamina: 80, stealth: 50, intelligence: 65, charm: 50, vocal: 65 }, move: { name: "Dabble Sweep", desc: "Sweeps the surface for seeds and insects with that iconic red-spotted bill." }, facts: ["Distinctive yellow-tipped black bill with red spot", "Dabbles at the water's surface", "One of India's resident ducks"] },
  { num: 62, name: "Eurasian Moorhen", sci: "Gallinula chloropus", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Waterfowl", region: "Pan-Indian", rarity: "Common", hp: 65, title: "The Lily Walker", stats: { speed: 60, stamina: 70, stealth: 55, intelligence: 70, charm: 50, vocal: 70 }, move: { name: "Pad Stride", desc: "Strides across floating lily pads on impossibly long toes." }, facts: ["Bright red bill with yellow tip", "Flicks white tail constantly", "Walks on lily pads with long toes"] },
  { num: 63, name: "Bronze-winged Jacana", sci: "Metopidius indicus", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 60, title: "The Floating-Foot Wonder", stats: { speed: 55, stamina: 70, stealth: 50, intelligence: 70, charm: 45, vocal: 65 }, move: { name: "Lily Step", desc: "Spreads enormous toes to walk on lily pads as if on solid ground." }, facts: ["Walks on floating vegetation with huge toes", "Females are larger and polyandrous", "Iridescent bronze-green plumage"] },
  { num: 64, name: "Green Sandpiper", sci: "Tringa ochropus", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Forager", region: "Pan-Indian", rarity: "Uncommon", hp: 45, title: "The White-Rumped Drifter", stats: { speed: 75, stamina: 95, stealth: 70, intelligence: 60, charm: 40, vocal: 60 }, move: { name: "Migrant's Path", desc: "Travels thousands of kilometres from northern Europe to winter on Indian wetlands." }, facts: ["Distinctive white rump in flight", "Bobs constantly while feeding", "Migrates from northern Europe and Asia"] },
  { num: 65, name: "Little Cormorant", sci: "Microcarbo niger", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Common", hp: 65, title: "The Tiny Diver", stats: { speed: 65, stamina: 75, stealth: 55, intelligence: 70, charm: 50, vocal: 40 }, move: { name: "Wing-Spread Dry", desc: "Stands wings outspread on a stump to dry after every dive." }, facts: ["Smallest cormorant in India", "Dives 1-2 meters deep for fish", "Often perches with wings outstretched"] },
  { num: 66, name: "Great Cormorant", sci: "Phalacrocorax carbo", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 110, title: "The Master Diver", stats: { speed: 70, stamina: 85, stealth: 55, intelligence: 80, charm: 40, vocal: 45 }, move: { name: "30-Metre Dive", desc: "Plunges to depths of 30+ metres; once trained by Chinese fishermen for centuries." }, facts: ["Largest cormorant species globally", "Used by Chinese fishermen for centuries", "Can dive to 30+ meters depth"] },
  { num: 67, name: "Great Egret", sci: "Ardea alba", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 110, title: "The White Sentinel", stats: { speed: 65, stamina: 80, stealth: 80, intelligence: 80, charm: 35, vocal: 50 }, move: { name: "Lightning Strike", desc: "Stands motionless for an hour, then strikes faster than you can blink." }, facts: ["Tallest of the white egrets — 1m tall", "Stands motionless then strikes lightning-fast", "Symbol of the National Audubon Society"] },
  { num: 68, name: "Medium Egret", sci: "Ardea intermedia", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 90, title: "The In-Between Egret", stats: { speed: 65, stamina: 75, stealth: 75, intelligence: 75, charm: 40, vocal: 45 }, move: { name: "Patience Plume", desc: "Develops gossamer breeding plumes in spring and waits, statue-still, for prey." }, facts: ["Sized between Great and Little Egrets", "Develops fine breeding plumes in spring", "Hunts in shallow water"] },
  { num: 69, name: "Gray Heron", sci: "Ardea cinerea", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Wetland", behavior: "Hunter", region: "Pan-Indian", rarity: "Uncommon", hp: 120, title: "The Silent Pillar", stats: { speed: 65, stamina: 85, stealth: 80, intelligence: 85, charm: 35, vocal: 60 }, move: { name: "Hour-Long Stand", desc: "Stands silent and statuesque for an hour; the wait is the weapon." }, facts: ["Stands silently for hours waiting for prey", "Wingspan up to 2 meters", "Distinctive black eyebrow stripe"] },
  { num: 70, name: "Oriental Magpie-Robin", sci: "Copsychus saularis", date: "22 Mar 2026", loc: "Chikkathogur Lake, Karnataka", habitat: "Urban", behavior: "Songbird", region: "Pan-Indian", rarity: "Common", hp: 50, title: "The Tuxedo Tenor", stats: { speed: 75, stamina: 60, stealth: 50, intelligence: 75, charm: 75, vocal: 95 }, move: { name: "Dawn Concerto", desc: "Sings before sunrise from the highest perch; the national bird of Bangladesh." }, facts: ["National bird of Bangladesh", "Sweet melodious whistling song", "Bold black-and-white plumage, cocked tail"] },
  { num: 71, name: "Indian Peafowl", sci: "Pavo cristatus", date: "22 Mar 2026", loc: "Godrej Ecity, Karnataka", habitat: "Forest", behavior: "Forager", region: "Pan-Indian", rarity: "Mythic", hp: 150, title: "The Iridescent Emperor", stats: { speed: 50, stamina: 75, stealth: 10, intelligence: 80, charm: 60, vocal: 85 }, move: { name: "Thousand-Eye Display", desc: "Unfurls a five-foot iridescent train of ~200 eye-shapes; absolutely no contest." }, facts: ["National bird of India since 1963", "Males grow 5-foot iridescent train", "Train feathers have ~200 'eye' patterns"] }
];

// Habitat / behavior / region meta (preserved from original; with grad colors)
window.HABITAT_META = {
  "Forest":    { emoji: "🌲", grad: "linear-gradient(135deg,#0e3b2e,#0a6b4e)", accent: "#22c55e" },
  "Wetland":   { emoji: "💧", grad: "linear-gradient(135deg,#0b2a55,#1c6fb9)", accent: "#38bdf8" },
  "Grassland": { emoji: "🌾", grad: "linear-gradient(135deg,#4a3a0e,#a17b22)", accent: "#facc15" },
  "Mountain":  { emoji: "⛰️", grad: "linear-gradient(135deg,#1e293b,#475569)", accent: "#94a3b8" },
  "Urban":     { emoji: "🏙️", grad: "linear-gradient(135deg,#3a0d4e,#8b2bb5)", accent: "#c084fc" },
  "Sky":       { emoji: "☁️", grad: "linear-gradient(135deg,#1e3a8a,#60a5fa)", accent: "#bfdbfe" }
};
window.BEHAVIOR_META = {
  "Forager":   { emoji: "🌰" },
  "Hunter":    { emoji: "🎯" },
  "Songbird":  { emoji: "🎶" },
  "Climber":   { emoji: "🧗" },
  "Raptor":    { emoji: "🦅" },
  "Waterfowl": { emoji: "🦆" }
};
window.REGION_META = {
  "Pan-Indian":     { emoji: "🇮🇳" },
  "Himalayan":      { emoji: "🏔️" },
  "South Indian":   { emoji: "🌴" },
  "Western Ghats":  { emoji: "🌿" }
};
window.RARITY_META = {
  "Common":    { emoji: "🪶", color: "#9ca3af", bg: "rgba(156,163,175,.18)", glow: "rgba(156,163,175,.4)" },
  "Uncommon":  { emoji: "🌿", color: "#34d399", bg: "rgba(52,211,153,.18)",  glow: "rgba(52,211,153,.4)" },
  "Rare":      { emoji: "💎", color: "#60a5fa", bg: "rgba(96,165,250,.18)",  glow: "rgba(96,165,250,.5)" },
  "Epic":      { emoji: "🔮", color: "#c084fc", bg: "rgba(192,132,252,.2)",  glow: "rgba(192,132,252,.55)" },
  "Legendary": { emoji: "👑", color: "#fbbf24", bg: "rgba(251,191,36,.22)",  glow: "rgba(251,191,36,.6)" },
  "Mythic":    { emoji: "✨", color: "#f472b6", bg: "rgba(244,114,182,.22)", glow: "rgba(244,114,182,.7)" }
};
window.STAT_META = {
  speed:        { label: "SPEED",   emoji: "⚡", color: "#fbbf24", desc: "How quickly it darts, dives, or chases. 100 = lightning." },
  stamina:      { label: "STAMINA", emoji: "🔋", color: "#84cc16", desc: "Endurance for long flights, migration, and patient hunts." },
  stealth:      { label: "STEALTH", emoji: "👁️‍🗨️", color: "#a78bfa", desc: "How well it hides — camouflage, silence, ambush skill." },
  intelligence: { label: "BRAINS",  emoji: "🧠", color: "#22d3ee", desc: "Problem solving, mimicry, tool use, memory." },
  charm:        { label: "CHARM",   emoji: "💛", color: "#f472b6", desc: "Tolerance of humans and other species nearby." },
  vocal:        { label: "VOCAL",   emoji: "🎙️", color: "#fb7185", desc: "Range and complexity of calls and song." }
};

// Stock images (preserved from original list)
window.BIRD_IMAGES = window.BIRD_IMAGES || {};
